# Generated by Django 5.1.2 on 2024-11-28 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_order_date_poshtibani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 11, 29, 50, 308719)),
        ),
    ]
