# Generated by Django 5.1.2 on 2024-11-28 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshtibani',
            name='username',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 12, 28, 13, 382542)),
        ),
    ]
