# Generated by Django 5.1.2 on 2024-11-28 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_order_date_alter_ticket_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 13, 10, 2, 90163)),
        ),
    ]
