# Generated by Django 5.1.2 on 2024-11-28 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 13, 10, 34, 75706)),
        ),
    ]
