# Generated by Django 5.1.2 on 2024-12-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_product_color_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 1, 17, 3, 44, 103942)),
        ),
    ]
