# Generated by Django 5.1.2 on 2024-12-02 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_profile_old_color_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_color',
        ),
        migrations.AddField(
            model_name='profile',
            name='old_save',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 2, 21, 48, 10, 176333)),
        ),
    ]
