# Generated by Django 5.1.2 on 2024-12-02 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_remove_profile_old_color_profile_old_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 2, 23, 37, 54, 591779)),
        ),
    ]
