# Generated by Django 5.1.2 on 2024-12-04 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0032_order_price_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 4, 17, 32, 38, 679060)),
        ),
    ]
