# Generated by Django 5.1.2 on 2024-12-04 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0033_order_is_sale_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 4, 17, 35, 46, 294177)),
        ),
    ]
