# Generated by Django 5.1.2 on 2024-12-04 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0034_order_sale_price_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 4, 18, 5, 44, 64243)),
        ),
    ]
