# Generated by Django 5.1.2 on 2024-12-09 15:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0048_order_color_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 19, 11, 11, 218564)),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
