# Generated by Django 5.1.2 on 2024-12-09 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0049_alter_order_date_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 19, 11, 36, 833874)),
        ),
    ]
