# Generated by Django 5.1.2 on 2024-12-11 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0053_allinone_address_allinone_city_allinone_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allinone',
            old_name='address',
            new_name='address1',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 23, 27, 5, 953857)),
        ),
    ]
